export const GET_DATA_REQUEST="GET_DATA_REQUEST";
export const GET_DATA_SUCCESS="GET_DATA_SUCCESS";
export const GET_DATA_FAILURE="GET_DATA_FAILURE";

export const EDIT_DATA_REQUEST="EDIT_DATA_REQUEST";
export const EDIT_DATA_SUCCESS="EDIT_DATA_SUCCESS";
export const EDIT_DATA_FAILURE="EDIT_DATA_FAILURE";