export const GET_TASKS_REQUEST="GET_TASKS_REQUEST";
export const GET_TASKS_SUCCESS="GET_TASKS_SUCCESS";
export const GET_TASKS_FAILURE="GET_TASKS_FAILURE";

export const ADD_TASKS_REQUEST="ADD_TASKS_REQUEST";
export const ADD_TASKS_SUCCESS="ADD_TASKS_SUCCESS";
export const ADD_TASKS_FAILURE="ADD_TASKS_FAILURE";